listening-port=3478
tls-listening-port=5349
min-port=49160
max-port=49200
realm=chatapp.shikpooshaan.ir
server-name=chatapp.shikpooshaan.ir
use-auth-secret
static-auth-secret=6f1e4518d8208cbc2f3e4aba926dee30f13363fd2d6b616922190d31a6d31f2d
lt-cred-mech
no-tlsv1
no-tlsv1_1
no-cli
verbose
external-ip=45.129.36.41/28
